#!/usr/bin/env python3

# ./baksmali [input].apk
# unzip an apk file and dissemble it to .smali files(in AndroidOutput dir)
# open the .smali dir in vscode

import subprocess as sp
import sys
import os

baksmaliOut = "/Users/esaki/AndroidStudioProjects/baksmaliOut"
unzipOut = "/Users/esaki/AndroidStudioProjects/unzipOut"

if(len(sys.argv) != 2):
    print("usage: ./baksmali [input.apk]")
    sys.exit(1)

apk = sys.argv[1].split('/')[-1]
apkname = apk.split('.')[0]

if(os.access(unzipOut+"/"+apkname, os.F_OK)):
    print("baksmaliOut exists.")
    print("open in code")
    sp.call(["code",baksmaliOut+"/"+apkname])
    exit(0)

# make dir to store smali files
sp.call([
    "mkdir",unzipOut+"/"+apkname
])
# unzip apk
sp.call([
    "unzip", "-q",
    sys.argv[1],
    "-d",unzipOut+"/"+apkname
])
# baksmali
sp.call([
    "java", "-jar","baksmali-2.2.5.jar", 
    "disassemble",
    "-o",baksmaliOut+"/"+apkname,
    unzipOut+"/"+apkname+"/classes.dex"
])
# open with vscode 
print("open in code")
sp.call([
    "code",baksmaliOut+"/"+apkname
])