#!/usr/bin/env python3

# ./myBaksmali [input].apk
# unzip an apk file and dissemble it to .smali files(in AndroidOutput dir)
# open the .smali dir in vscode

import subprocess as sp
import sys
import os

baksmaliOut = "/Users/esaki/AndroidStudioProjects/baksmaliOut"
unzipOut = "/Users/esaki/AndroidStudioProjects/unzipOut"


def baksmali():
    if len(sys.argv) != 2:
        print("usage: ./myBaksmali [input.apk]")
        sys.exit(1)

    apkname = sys.argv[1].split('/')[-1].split('.')[0]
    if os.access(unzipOut+"/"+apkname, os.F_OK):
        sp.check_call(["rm", "-rf", unzipOut+"/"+apkname])
        sp.check_call(["rm", "-rf", baksmaliOut+"/"+apkname])

    commands = [
        [
            "mkdir", unzipOut+"/"+apkname
        ], [
            "unzip", "-q",
            sys.argv[1],
            "-d", unzipOut+"/"+apkname
        ], [
            "java", "-jar", "baksmali-2.2.5.jar",
            "disassemble",
            "-o", baksmaliOut+"/"+apkname,
            unzipOut+"/"+apkname+"/classes.dex"
        ], [
            "code", baksmaliOut+"/"+apkname
        ]
    ]
    for command in commands:
        sp.check_call(command)

baksmali()